rd /s /q artifacts
rd /s /q Record
rd /s /q BlackVueDownloader\bin
rd /s /q BlackVueDownloader\obj
rd /s /q BlackVueDownloader.PCL\bin
rd /s /q BlackVueDownloader.PCL\obj
rd /s /q BlackVueDownloader.Tests\bin
rd /s /q BlackVueDownloader.Tests\obj
rd /s /q BlackVueDownloader.Tests\Record
